"""test

Revision ID: fb7fb976a2c1
Revises:
Create Date: 2026-08-17 07:53:29.268716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fb7fb976a2c1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contents", sa.Column("is_enabled", sa.Boolean(), nullable=True))
    op.add_column("questions", sa.Column("is_enabled", sa.Boolean(), nullable=True))

    op.execute("UPDATE contents SET is_enabled = TRUE")
    op.execute("UPDATE questions SET is_enabled = TRUE")

    op.alter_column("contents", "is_enabled", nullable=False)
    op.alter_column("questions", "is_enabled", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "is_enabled")
    op.drop_column("contents", "is_enabled")
    # ### end Alembic commands ###
